# ET Intelligence Configuration File
# Copy this to .et-intel.yml and customize

# Database connection
database_url: "postgresql://user:password@localhost:5432/et_intel"

# Sentiment analysis backend
# Options: rule_based, openai, hybrid
sentiment_backend: "hybrid"

# OpenAI API key (required for openai or hybrid backends)
openai_api_key: "your-api-key-here"

# Default options for CLI commands
defaults:
  # Enrichment
  enrichment_batch_size: 50
  
  # Analytics
  velocity_window_hours: 72
  velocity_min_sample_size: 10
  
  # Reporting
  top_entities_limit: 20
  history_days: 30

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance
performance:
  batch_commit_size: 100
  query_timeout_seconds: 30

