"""Add signal indexes for performance

Revision ID: b3d3384be058
Revises: 16accb8125c7
Create Date: 2025-11-26 18:08:23.222952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d3384be058'
down_revision: Union[str, None] = '16accb8125c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_signals_comment', 'extracted_signals', ['comment_id'], unique=False)
    op.create_index('ix_signals_entity_type', 'extracted_signals', ['entity_id', 'signal_type'], unique=False)
    op.create_index('ix_signals_numeric', 'extracted_signals', ['signal_type', 'numeric_value'], unique=False)
    op.create_index('ix_signals_type', 'extracted_signals', ['signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_type', table_name='extracted_signals')
    op.drop_index('ix_signals_numeric', table_name='extracted_signals')
    op.drop_index('ix_signals_entity_type', table_name='extracted_signals')
    op.drop_index('ix_signals_comment', table_name='extracted_signals')
    # ### end Alembic commands ###

